In [3]:
import cv2
import os
from PIL import Image
import numpy as np

## Exportación frames

In [52]:
vidcap = cv2.VideoCapture('../data/ruido_videos/merge.mp4')

In [53]:
def getFrame(sec):
    vidcap.set(cv2.CAP_PROP_POS_MSEC,sec*1000)
    hasFrames,image = vidcap.read()
    if hasFrames:
        cv2.imwrite("../data/ruido_fotos/pic"+str(count)+".jpg", image)
    return hasFrames
sec = 0
frameRate = 1/30
count=1
success = getFrame(sec)
while success:
    count = count + 1
    sec = sec + frameRate
    sec = round(sec, 2)
    success = getFrame(sec)

## Dataset a partir de imagen

In [58]:

from resizeimage import resizeimage

for i in range(1,5510):
    with open('../data/ruido_fotos/pic{}.jpg'.format(i), 'r+b') as f:
        with Image.open(f) as image:
            cover = resizeimage.resize_cover(image, [28, 28])
            cover.save('../data/resized_fotos/pic{}.jpeg'.format(i), image.format)

In [ ]:
for i in range(1,5510):
    with open('../data/resized_fotos/pic{}.jpeg'.format(i), 'r+b') as f:
        with Image.open(f) as image:
            img = image.convert('L')
            img.save('../data/resized_bw/pic{}.jpeg'.format(i))

### Imágenes (28,28) a array

In [62]:
noise = pd.DataFrame()
for i in range(1,5510):
    with open('../data/resized_bw/pic{}.jpeg'.format(i), 'r+b') as f:
        with Image.open(f) as image:
            arr = np.array(image)
            noise = noise.append(pd.Series(arr.flatten()), ignore_index=True)

In [63]:
noise["label"] = "other"

In [64]:
noise

,0,1,2,3,4,5,6,7,8,9,...,775,776,777,778,779,780,781,782,783,label
0,73.0,91.0,102.0,97.0,81.0,101.0,80.0,75.0,74.0,64.0,...,92.0,88.0,90.0,181.0,213.0,207.0,171.0,170.0,97.0,other
1,79.0,85.0,101.0,94.0,89.0,91.0,77.0,77.0,70.0,67.0,...,97.0,82.0,93.0,201.0,207.0,197.0,152.0,170.0,100.0,other
2,68.0,86.0,102.0,89.0,87.0,88.0,71.0,75.0,70.0,66.0,...,91.0,82.0,121.0,218.0,198.0,192.0,159.0,168.0,101.0,other
3,66.0,95.0,98.0,86.0,88.0,81.0,70.0,75.0,68.0,56.0,...,96.0,84.0,143.0,206.0,194.0,194.0,163.0,163.0,93.0,other
4,66.0,95.0,98.0,86.0,88.0,81.0,70.0,75.0,68.0,56.0,...,96.0,84.0,143.0,206.0,194.0,194.0,163.0,163.0,93.0,other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5504,67.0,119.0,117.0,83.0,112.0,119.0,143.0,142.0,144.0,127.0,...,71.0,69.0,69.0,72.0,74.0,81.0,82.0,86.0,44.0,other
5505,63.0,118.0,119.0,85.0,111.0,117.0,144.0,146.0,149.0,122.0,...,71.0,69.0,69.0,72.0,74.0,79.0,84.0,87.0,43.0,other
5506,60.0,118.0,111.0,92.0,107.0,121.0,138.0,147.0,143.0,120.0,...,72.0,69.0,69.0,71.0,72.0,76.0,83.0,88.0,44.0,other
5507,66.0,111.0,115.0,87.0,103.0,128.0,132.0,151.0,145.0,128.0,...,72.0,69.0,69.0,71.0,72.0,78.0,83.0,86.0,42.0,other
5508,64.0,108.0,122.0,97.0,100.0,121.0,131.0,151.0,141.0,126.0,...,72.0,69.0,69.0,71.0,72.0,77.0,83.0,89.0,44.0,other

In [65]:
noise.to_csv("../data/processed/background.csv", index=False)

## Mejoro dataset con otros gestos como ruido

In [66]:
train = pd.read_csv("../data/sign_mnist/sign_mnist_train.csv")

In [67]:
newLabels = {0: "A", 1: "B", 2: "C", 3: "D", 4: "E", 5: "F", 6: "G",
            7: "H", 8: "I", 10: "K", 11: "L", 12: "M", 13: "N",
            14: "O", 15: "P", 16: "Q", 17: "R", 18:"S",
            19: "T", 20:"U", 21:"V", 22:"W", 23:"X",
            24:"Y"}

train["label"] = train["label"].map(newLabels)

In [95]:
signs = ["A", "B", "F", "T", "V", "Y"]

morenoise = train[(train.label != "A") & (train.label != "B") & (train.label != "F") & (train.label != "T")
              & (train.label != "V") & (train.label != "Y")]

In [98]:
morenoise.label = "other"

In [99]:
morenoise

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,other,107,118,127,134,139,143,146,150,153,...,207,207,207,207,206,206,206,204,203,202
1,other,155,157,156,156,156,157,156,158,158,...,69,149,128,87,94,163,175,103,135,149
2,other,187,188,188,187,187,186,187,188,187,...,202,201,200,199,198,199,198,195,194,195
3,other,211,211,212,212,211,210,211,210,210,...,235,234,233,231,230,226,225,222,229,163
4,other,164,167,170,172,176,179,180,184,185,...,92,105,105,108,133,163,157,163,164,179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27450,other,189,189,190,190,192,193,193,193,193,...,132,165,99,77,52,200,234,200,222,225
27451,other,151,154,157,158,160,161,163,164,166,...,198,198,198,198,198,196,195,195,195,194
27452,other,174,174,174,174,174,175,175,174,173,...,121,196,209,208,206,204,203,202,200,200
27453,other,177,181,184,185,187,189,190,191,191,...,119,56,27,58,102,79,47,64,87,93
27454,other,179,180,180,180,182,181,182,183,182,...,108,132,170,194,214,203,197,205,209,215

In [100]:
morenoise.to_csv("../data/processed/morenoise.csv", index=False)

In [92]:
data = pd.read_csv("../data/processed/data.csv")

In [101]:
noisyData = pd.concat([morenoise, data])

In [104]:
noisyData.label.value_counts()

other    26238
A         1457
F         1451
Y         1450
B         1442
T         1434
V         1428
Name: label, dtype: int64

In [ ]:
noisyData.to_csv("../data/processed/noisyData.csv", index=False)