In [3]:
import cv2
import os
from PIL import Image
import numpy as np

## Exportación frames

In [52]:
vidcap = cv2.VideoCapture('../data/ruido_videos/merge.mp4')

In [53]:
def getFrame(sec):
    vidcap.set(cv2.CAP_PROP_POS_MSEC,sec*1000)
    hasFrames,image = vidcap.read()
    if hasFrames:
        cv2.imwrite("../data/ruido_fotos/pic"+str(count)+".jpg", image)
    return hasFrames
sec = 0
frameRate = 1/30
count=1
success = getFrame(sec)
while success:
    count = count + 1
    sec = sec + frameRate
    sec = round(sec, 2)
    success = getFrame(sec)

## Dataset a partir de imagen

In [58]:

from resizeimage import resizeimage

for i in range(1,5510):
    with open('../data/ruido_fotos/pic{}.jpg'.format(i), 'r+b') as f:
        with Image.open(f) as image:
            cover = resizeimage.resize_cover(image, [28, 28])
            cover.save('../data/resized_fotos/pic{}.jpeg'.format(i), image.format)

In [ ]:
for i in range(1,5510):
    with open('../data/resized_fotos/pic{}.jpeg'.format(i), 'r+b') as f:
        with Image.open(f) as image:
            img = image.convert('L')
            img.save('../data/resized_bw/pic{}.jpeg'.format(i))

### Imágenes (28,28) a array

In [54]:
noise = pd.DataFrame()
for i in range(1,5510):
    with open('../data/resized_bw/pic{}.jpeg'.format(i), 'r+b') as f:
        with Image.open(f) as image:
            arr = np.array(image)
            noise = noise.append(pd.Series(arr.flatten()), ignore_index=True)

In [58]:
noise["label"] = "other"

In [59]:
noise

,0,1,2,3,4,5,6,7,8,9,...,775,776,777,778,779,780,781,782,783,label
0,73.0,91.0,102.0,97.0,81.0,101.0,80.0,75.0,74.0,64.0,...,92.0,88.0,90.0,181.0,213.0,207.0,171.0,170.0,97.0,other
1,79.0,85.0,101.0,94.0,89.0,91.0,77.0,77.0,70.0,67.0,...,97.0,82.0,93.0,201.0,207.0,197.0,152.0,170.0,100.0,other
2,68.0,86.0,102.0,89.0,87.0,88.0,71.0,75.0,70.0,66.0,...,91.0,82.0,121.0,218.0,198.0,192.0,159.0,168.0,101.0,other
3,66.0,95.0,98.0,86.0,88.0,81.0,70.0,75.0,68.0,56.0,...,96.0,84.0,143.0,206.0,194.0,194.0,163.0,163.0,93.0,other
4,66.0,95.0,98.0,86.0,88.0,81.0,70.0,75.0,68.0,56.0,...,96.0,84.0,143.0,206.0,194.0,194.0,163.0,163.0,93.0,other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5504,67.0,119.0,117.0,83.0,112.0,119.0,143.0,142.0,144.0,127.0,...,71.0,69.0,69.0,72.0,74.0,81.0,82.0,86.0,44.0,other
5505,63.0,118.0,119.0,85.0,111.0,117.0,144.0,146.0,149.0,122.0,...,71.0,69.0,69.0,72.0,74.0,79.0,84.0,87.0,43.0,other
5506,60.0,118.0,111.0,92.0,107.0,121.0,138.0,147.0,143.0,120.0,...,72.0,69.0,69.0,71.0,72.0,76.0,83.0,88.0,44.0,other
5507,66.0,111.0,115.0,87.0,103.0,128.0,132.0,151.0,145.0,128.0,...,72.0,69.0,69.0,71.0,72.0,78.0,83.0,86.0,42.0,other
5508,64.0,108.0,122.0,97.0,100.0,121.0,131.0,151.0,141.0,126.0,...,72.0,69.0,69.0,71.0,72.0,77.0,83.0,89.0,44.0,other

In [60]:
noise.to_csv("../data/processed/background.csv")